au! BufNewFile,BufRead *.tx setf html
au! BufNewFile,BufRead *.tt setf html
au! BufNewFile,BufRead *.t setf perl
au! BufNewFile,BufRead *.perl setf perl
au! BufNewFile,BufRead *.psgi setf perl
au! BufNewFile,BufRead *.scss setf css
au! BufNewFile,BufRead *.json setf json
au! BufNewFile,BufRead *.go setf go
au! BufNewFile,BufRead Vagrantfile setf ruby
